development:
  adapter: postgresql
  host: localhost
  username: development
  password: development
  database: development
  pool: 1

test:
  adapter: postgresql
  host: localhost
  username: test
  password: test
  database: test
  pool: 3

production:
  adapter: postgresql
  host: localhost
  username: imalog
  password: "im@l0gProduction"
  database: imalog
  pool: 10
